- hosts: serveurs
  become: yes
  tasks:
    - name: Kill tous les processus git
      shell: pkill -9 git || true
      ignore_errors: yes

    - name: Nettoyer tout le home directory
      shell: |
        rm -rf /home/mathis.oudin-gcp/app*
        rm -rf /home/mathis.oudin-gcp/my-app*
        rm -rf /home/mathis.oudin-gcp/nextjs-app*
        rm -rf /home/mathis.oudin-gcp/.git*
        rm -rf /tmp/nextjs*
        rm -rf /tmp/my-app*
        rm -rf /var/www/nextjs*
      ignore_errors: yes

    - name: Nettoyer les lock files
      shell: find /home/mathis.oudin-gcp -name "*.lock" -delete
      ignore_errors: yes

    - name: Réinstaller git
      apt:
        name: git
        state: absent

    - name: Installer git proprement
      apt:
        name: git
        state: present
        update_cache: yes
